#ifndef ZEROOS_FONT_H
#define ZEROOS_FONT_H

#define FONT_DEFAULT_FONT_W 8
#define FONT_DEFAULT_FONT_H 16
#define FONT_DEFAULT_FONT_NUM_CHAR 96

extern const unsigned char default_font[FONT_DEFAULT_FONT_NUM_CHAR][FONT_DEFAULT_FONT_H];

#endif //ZEROOS_FONT_H
